Design/publishing enroll page
SV-Summer-BootCamp-Team-F/frontend pull request #18
Opened 2023-07-17 06:19 UTC by ajaj0123

## 📖 개요
<img width="596" alt="image" src="https://github.com/SV-Summer-BootCamp-Team-F/frontend/assets/86238348/f93164e2-00e3-4b01-983e-8631660a261d">

## 💻 작업사항

-

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-07-17 06:28 UTC, TMInstaller requested changes
변경이 필요한 부분에 대한 리뷰 남깁니다
폴더구조의 경우 적절하게 적용된 것 같습니다~

2023-07-17 06:28 UTC, TMInstaller commented on src/css/Enroll.css
tailwindCSS로 바꿀 수 있는 그리 복잡하지 않은 스타일 같아 보이네요..!
혹시 그렇게 수정이 가능할까요?

2023-07-17 06:28 UTC, TMInstaller commented on src/pages/Card/EnrollPage.tsx
> +          Remember <span style={{ color: "skyblue" }}>plus+</span>
권장되지 않는 inline-style tag를 사용하신 이유가 있나요??
이 부분은 tailwind로 충분히 바뀔 수 있을 것 같습니다!

2023-07-17 12:28 UTC, ajaj0123 commented on src/pages/Card/EnrollPage.tsx
> +          Remember <span style={{ color: "skyblue" }}>plus+</span>
수정 완료했습니다!

2023-07-17 12:29 UTC, ajaj0123 commented on src/css/Enroll.css
tailwindCSS로 변경 완료했습니다!

2023-07-17 17:41 UTC, TMInstaller approved these changes
고생하셨습니다~ 이제 병합하셔도 좋습니다!

2023-07-18 08:53 UTC, TMInstaller approved these changes
이제 merge하셔도 좋습니다.

2023-07-18 12:39 UTC, merged