Design/design update user information page 21
SV-Summer-BootCamp-Team-F/frontend pull request #25
Opened 2023-07-19 06:43 UTC by rachel4w2

## 📖 개요
<img width="1512" alt="스크린샷 2023-07-19 오후 3 41 01" src="https://github.com/SV-Summer-BootCamp-Team-F/frontend/assets/87238236/c2a52b7a-9bec-41bc-993e-1687b672358d">
<img width="1512" alt="스크린샷 2023-07-19 오후 3 41 12" src="https://github.com/SV-Summer-BootCamp-Team-F/frontend/assets/87238236/02cec775-351a-466e-9e97-63335ca3eded">

## 💻 작업사항
- 유저 페이지 전체 레이아웃 수정
- Dashboard 구성 변경

## 💡 작성한 이슈 외에 작업한 사항
-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-07-19 07:17 UTC, TMInstaller requested changes
좋습니다. 추가 요청사항입니다!

2023-07-19 07:17 UTC, TMInstaller commented on src/components/analytic/StatisticsBox.tsx
> +}
type을 하나로 맞춰두는 것도 좋은 생각이에요
interface 대신 type으로,
StatisticsBoxProps 대신 StatisticsBoxPropsType로 사용해보는건 어떨까요?

2023-07-19 07:17 UTC, TMInstaller commented on src/components/card/CardInfo.tsx
> +}
여기도 마찬가지입니다!

2023-07-19 07:17 UTC, TMInstaller commented on src/components/card/CardInfo.tsx
> +  "h-[90px] w-[200px] text-[15px] text-black bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-xl text-4xl dark:bg-gray-800 dar
잘 나눠두신 것 같습니다. 아얘 이런 부분들만을 모아서 후에 따로 파일로 분리해도 괜찮을 것 같네요!

2023-07-19 07:17 UTC, TMInstaller commented on src/pages/User/UserPage.tsx
> +}
변경 부탁드립니다!

2023-07-20 06:03 UTC, rachel4w2 commented on src/components/analytic/StatisticsBox.tsx
> +}
넵 수정했습니다!😀

2023-07-20 06:04 UTC, rachel4w2 commented on src/components/card/CardInfo.tsx
> +}
넵 수정했습니다!😁

2023-07-20 06:05 UTC, rachel4w2 commented on src/components/card/CardInfo.tsx
> +  "h-[90px] w-[200px] text-[15px] text-black bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-xl text-4xl dark:bg-gray-800 dar
넵 비슷하게 className이 길어지는 컴포넌트들이 많아지면 분리해보도록 하겠습니다!👍

2023-07-20 06:05 UTC, rachel4w2 commented on src/pages/User/UserPage.tsx
> +}
넵 수정했습니다!😄

2023-07-20 06:11 UTC, TMInstaller approved these changes

2023-07-20 06:12 UTC, merged